"""Ateracao-imagens-usario-produto

Revision ID: 8a55c3209d4b
Revises: d6a93cca2184
Create Date: 2022-12-11 21:48:37.156412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a55c3209d4b'
down_revision = 'd6a93cca2184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
