"""primeira_migracao

Revision ID: d6a93cca2184
Revises: 
Create Date: 2022-11-30 13:09:00.825003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a93cca2184'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento_cartao')
    op.drop_table('item_carrinho')
    op.drop_index('ix_vendedor_identificado', table_name='vendedor')
    op.drop_index('ix_vendedor_nome', table_name='vendedor')
    op.drop_table('vendedor')
    op.drop_table('produtos')
    op.drop_table('licencas')
    op.drop_table('usuario-google')
    op.drop_table('carrinho')
    op.drop_table('historico_compra_usuario')
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('imagens')
    op.drop_table('imagens_produtos')
    op.drop_table('enderecos')
    op.drop_table('avaliacao-produtos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao-produtos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comentario_usuario', sa.VARCHAR(length=256), nullable=True),
    sa.Column('nota_produto', sa.FLOAT(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rua', sa.VARCHAR(length=256), nullable=False),
    sa.Column('numero', sa.INTEGER(), nullable=False),
    sa.Column('bairro', sa.VARCHAR(length=256), nullable=False),
    sa.Column('cep', sa.VARCHAR(length=8), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagens_produtos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=256), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=256), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=256), nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(length=256), nullable=False),
    sa.Column('celular', sa.VARCHAR(length=13), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=False)
    op.create_table('historico_compra_usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('identificado_usuario', sa.VARCHAR(length=14), nullable=False),
    sa.Column('preco_produto', sa.VARCHAR(length=256), nullable=False),
    sa.Column('data_compra_pedido', sa.DATETIME(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario-google',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sub', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email', sa.VARCHAR(length=256), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=256), nullable=True),
    sa.Column('aud', sa.VARCHAR(length=256), nullable=True),
    sa.Column('azp', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('exp', sa.INTEGER(), nullable=True),
    sa.Column('family_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('give_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('iat', sa.INTEGER(), nullable=True),
    sa.Column('iss', sa.VARCHAR(length=256), nullable=True),
    sa.Column('jti', sa.VARCHAR(length=256), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('nbf', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licencas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('validade', sa.FLOAT(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=256), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=256), nullable=False),
    sa.Column('preco', sa.VARCHAR(length=50), nullable=False),
    sa.Column('detalhes', sa.VARCHAR(length=500), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=False),
    sa.Column('vendedor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('vendedor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('identificado', sa.VARCHAR(length=14), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=240), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendedor_nome', 'vendedor', ['nome'], unique=False)
    op.create_index('ix_vendedor_identificado', 'vendedor', ['identificado'], unique=False)
    op.create_table('item_carrinho',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento_cartao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_amount', sa.FLOAT(), nullable=True),
    sa.Column('token', sa.VARCHAR(length=256), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('installments', sa.INTEGER(), nullable=True),
    sa.Column('payment_method_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email', sa.VARCHAR(length=256), nullable=True),
    sa.Column('number', sa.VARCHAR(length=13), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
